<!DOCTYPE HTML>
<html>
<head>
    <title>JSP</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <style>
        .date { font-weight: bold; padding: 10px; font-size: larger; }
    </style>
</head>
<body>
    <p>Hello, <sitemesh:copy id="name">${name}</sitemesh:copy>!</p>

    <p>This page demonstrates that dynamic content can be decorated in the same way as static content.</p>
    <p>This is a simple JSP that shows the date and time on the server is now:</p>

    <div class='date'><%= new java.util.Date() %></div>

    <p>Of course, with SiteMesh you are not limited to JSP. Because it's a Servlet Filter, both content and decorators can be
        generated by any technology in your ServletEngine, including: <a href="/">static</a> files, <a href="/greeting">JSP</a>, Velocity, <a href="/greeting/ftl">FreeMarker</a>, <a href="/greeting/ttl">Thymeleaf</a>, JSF, MVC frameworks, JRuby.... you get the point.</p>

    <form>
        What is your name? <input type="text" name="name" />
        <input type="submit" value="Go" />
    </form>

    <sitemesh:cut id="jsSpecialGreeter">
        <script type="text/javascript">
            if ('${name}'.toLowerCase() == "scott") {
                alert("Now that's a cool name!!")
            }
        </script>
    </sitemesh:cut>
</body>
</html>