<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %><html>
  <head>
    <% if (request.getParameter("ex") != null) { throw new RuntimeException("This is a 500 error."); } %>
    <title>Hello World (Dynamic)</title>
    <c:if test="${not empty param.bootstrap}">
      <meta name="decorator" content="/WEB-INF/layouts/bootstrap.jsp${not empty param.doubled?',/WEB-INF/layouts/chaining.html':''}" />
    </c:if>
  </head>
  <body>
    <p>This page demonstrates that dynamic content can be decorated in the same way as static content.</p>
    <p>This is a simple JSP that shows the date and time on the server is now:</p>

    <h3><%= new java.util.Date() %></h3>

    <p>Of course, with SiteMesh you are not limited to JSP. Because it's a Servlet Filter, both content and decorators can be
    generated by any technology in your ServletEngine, including: static files, JSP, Velocity, FreeMarker, JSF, MVC frameworks, JRuby.... you get the point.</p>

  </body>
</html>